import {
  Activity,
  Archive,
  AudioLines,
  Brain,
  Building2,
  ClipboardCheck,
  ClipboardList,
  Eye,
  FileBadge,
  FileCheck,
  FileSearch,
  FileText,
  FlaskConical,
  HeartPulse,
  LayoutGrid,
  Map,
  Radiation,
  Scan,
  ShieldAlert,
  ShieldCheck,
  Stethoscope,
  TestTube,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  Wind,
  type LucideIcon,
} from "lucide-react";

export const SERVICE_ICON_MAP: Record<string, LucideIcon> = {
  "ASO Admissional": UserPlus,
  "ASO Demissional": UserMinus,
  "ASO Periódico": UserCheck,
  "Mudança de Função": Users,
  "Retorno ao Trabalho": ClipboardCheck,
  PCMSO: Stethoscope,
  PPP: FileBadge,
  LTCAT: FileSearch,
  "PGR — Programa de Gerenciamento de Riscos": ShieldCheck,
  "Laudo de Insalubridade": Radiation,
  "Laudo de Periculosidade": ShieldAlert,
  "Análise Ergonômica": Activity,
  APR: ClipboardList,
  CIPA: Users,
  "Mapa de Risco": Map,
  Audiometria: AudioLines,
  "Acuidade Visual": Eye,
  "Avaliação Oftalmológica": Eye,
  "Avaliação Psicológica": Brain,
  Eletrocardiograma: HeartPulse,
  Eletroencefalograma: Brain,
  Espirometria: Wind,
  "Raio-X": Scan,
  Tomografia: Scan,
  "Exames Laboratoriais": TestTube,
  Toxicológico: FlaskConical,
  "Eventos de SST no eSocial": Building2,
  "Organização documental ocupacional": LayoutGrid,
  "Controle de ASO e laudos": FileCheck,
  "Arquivo técnico ocupacional": Archive,
};

export function getServiceIcon(name: string, fallback: LucideIcon = FileText): LucideIcon {
  return SERVICE_ICON_MAP[name] ?? fallback;
}
