-- UserRole extensions (must commit before role migration in phase 1)
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CLINIC_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'RECEPTION';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COMMERCIAL';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FINANCIAL';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SST_TECHNICIAN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'HEALTH_PROFESSIONAL';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COMPANY_HR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'READ_ONLY';
