-- Enum extensions only — must run in a separate transaction before using new values.
-- PostgreSQL: ALTER TYPE ... ADD VALUE cannot be used in the same transaction as UPDATE/INSERT with that value.

-- ReferralStatus
ALTER TYPE "ReferralStatus" ADD VALUE IF NOT EXISTS 'AGUARDANDO_RESULTADO';
ALTER TYPE "ReferralStatus" ADD VALUE IF NOT EXISTS 'AGUARDANDO_DOCUMENTO';
ALTER TYPE "ReferralStatus" ADD VALUE IF NOT EXISTS 'ASO_DISPONIVEL';

-- PreReferralStatus
ALTER TYPE "PreReferralStatus" ADD VALUE IF NOT EXISTS 'AGUARDANDO_RETORNO';
ALTER TYPE "PreReferralStatus" ADD VALUE IF NOT EXISTS 'DUPLICADO';

-- AppointmentStatus
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'EM_ATENDIMENTO';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'CONCLUIDO';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'REAGENDADO';

-- CompanyStatus
ALTER TYPE "CompanyStatus" ADD VALUE IF NOT EXISTS 'ATIVA';
ALTER TYPE "CompanyStatus" ADD VALUE IF NOT EXISTS 'INATIVA';
ALTER TYPE "CompanyStatus" ADD VALUE IF NOT EXISTS 'PENDENTE';
ALTER TYPE "CompanyStatus" ADD VALUE IF NOT EXISTS 'BLOQUEADA';

-- DocumentType / DocumentStatus
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PGR';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'CONTRATO';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PROPOSTA';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'LAUDO_INSALUBRIDADE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'LAUDO_PERICULOSIDADE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'RESULTADO_EXAME';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'GUIA_ENCAMINHAMENTO';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PROPOSTA_ORCAMENTO';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'DOCUMENTO_ADMINISTRATIVO';

ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'EM_DIA';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'VENCIDO';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'ARQUIVADO';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'EM_EMISSAO';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'DISPONIVEL';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'ENVIADO';

-- LeadStatus
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'EXPIRADO';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'EM_ANALISE';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'AGUARDANDO_RETORNO';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CONVERTIDO_ORCAMENTO';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'ARQUIVADO';

-- PatientStatus
ALTER TYPE "PatientStatus" ADD VALUE IF NOT EXISTS 'ATIVO';
ALTER TYPE "PatientStatus" ADD VALUE IF NOT EXISTS 'INATIVO';
ALTER TYPE "PatientStatus" ADD VALUE IF NOT EXISTS 'AFASTADO';
ALTER TYPE "PatientStatus" ADD VALUE IF NOT EXISTS 'DESLIGADO';
ALTER TYPE "PatientStatus" ADD VALUE IF NOT EXISTS 'PENDENTE';

-- ExamCategory
ALTER TYPE "ExamCategory" ADD VALUE IF NOT EXISTS 'CLINICO_OCUPACIONAL';
ALTER TYPE "ExamCategory" ADD VALUE IF NOT EXISTS 'IMAGEM';
ALTER TYPE "ExamCategory" ADD VALUE IF NOT EXISTS 'TOXICOLOGICO';
ALTER TYPE "ExamCategory" ADD VALUE IF NOT EXISTS 'AVALIACAO_ESPECIALIZADA';

-- UserRole (Phase 1)
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CLINIC_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'RECEPTION';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COMMERCIAL';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FINANCIAL';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SST_TECHNICIAN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'HEALTH_PROFESSIONAL';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COMPANY_HR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'READ_ONLY';
